In [1]:
import numpy as np
# np.copy() and np.view()
# copy will create new array and copy the data whereas view will create new array and share the data
data=np.array([1,2,3,4,5,6])
# ndata=data.copy()
# data[0]=10
# print(ndata)

# VIEW
ndata=data.view()
data[0]=10
print(ndata)

[10  2  3  4  5  6]


In [2]:
import numpy as np
arr=np.array([1,2,3,4],[5,7,4,2],[3,5,62,2],[5,7,4,2])
for num in np.nditer(arr):
    print(arr)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [ ]:
# concatinate 
# stack  :vstack and hstack,  dstack
# split :horizontal vertical
# where
# searchsort

In [4]:
data=np.array([1,2,3,4,5,6])
np.where(data==3)

(array([2], dtype=int64),)

In [8]:
data=np.array([1,2,3,45,5])
a=np.searchsorted(data,1,side='right')
print(a)

1


In [1]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [2]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)


1
3
5
7


In [12]:
x=[1,23,4,6]
y=[1,2,4,5]
z=[]
for i, j in zip(x, y):
  z.append(i + j)
print(z)

[2, 25, 8, 11]


In [13]:
x=[1,23,4,6]
y=[1,2,4,5]
z=np.add(x,y)
z

array([ 2, 25,  8, 11])

In [8]:
import numpy as np

def addi(x,y):
    return x+y

addi=np.frompyfunc(addi,2,1)
print(addi([1,2,3],[3,4,6]))

TypeError: addi (vectorized)() takes from 8 to 9 positional arguments but 2 were given